bot_username: "IAmA-SSI-Bot"
bot_subreddit: "SubSimGPT2Interactive"
# bot_subreddit: "test"
bot_backstory: 'The following is part of an "Ask Me Anything" thread on Reddit.'
# To support systems like repl.it, the following are "secrets"
# so, instead of the actual values, enter the name of an environment variable where it's stored
reddit_pass_var: "IAMA_PASS"
reddit_ID_var: "IAMA_ID"
reddit_secret_var: "IAMA_SECRET"
HF_key_var: "HF_BEARER_ID"
# separate GPT-2 model for posts with SSI-style tagging
post_textgen_model: "umm-maybe/IAmA_GPT2"
# set to negative or zero for no posts
post_frequency: 0
reply_textgen_model: "EleutherAI/gpt-j-6B"
# force reply to top-level comments
force_top_reply: True
# restrict replies to comments on own posts/replies
followup_only: True
# base probability of commenting on a post or top-level comment
reply_chance: 0.1
# OPTIONAL, strings that automatically trigger a reply
trigger_words: ['who','what','where','when','why','how','?']
# increase in probability of a response if triggered (per word)
trigger_boost: 0.1
# minimum reply model (microsoft/DialogRPT-width) score to reply to comment
# score is a sigmoid, default of 0.5 corresponds to predicting at least 1 reply
min_reply_score: 0.5
# maximum number of comment levels up to accumulate in prompt
# also effectively the maximum number of levels down it can go
max_levels: 6
# maximum number of input characters per day - to manage Huggingface budgets
# default below is set so as to keep one bot within free plan limits
character_budget: 30000
# Text generation parameters
text_generation_parameters:
    max_new_tokens: 250 # cannot be more than 250, apparently
    num_return_sequences: 1
    temperature: 0.8
    top_k: 40
    repetition_penalty: 1.008
    stop_token: '<|endoftext|>' # I hope there is stop token but I don't think so
    return_full_text: False
    use_cache: False
# OPTIONAL, keywords that block a reply (ssi-bot default keywords included in script)
negative_keywords: []
# toxicity model rejection criteria
# minimum probability that a text classifies as NSFW, hate speech, or a threat to reject generation
threshold_map:
    nsfw: 0.9
    hate: 0.9
    threat: 0.9
