bot_username: "SpecialRequest_SSI"
bot_subreddit: "SubSimGPT2Interactive"
bot_backstory: 'u/SpecialRequest_SSI is an improv actor who can play any role on request.'
dynamic_prompt: True
reddit_pass: # enter password here
reddit_ID: # enter Reddit bot ID here
reddit_secret: # enter Reddit bot secret here
# The following are "secrets"
# so, instead of the actual values, enter the name of an environment variable where it's stored
# Huggingface Inference API key
HF_key_var: "HF_BEARER_ID"
# For Perspective API toxicity checking
Google_API_key_var: "GOOGLE_KEY"
# For image recognition
azure_token_var: "AZURE_KEY"
# Azure vision endpoint (not secret)
azure_endpoint: # your endpoint goes here
# For image upscaling
deepai_api_key_var: "DEEPAI_KEY"
# LLM for commenting
reply_textgen_model: "EleutherAI/gpt-neo-2.7B"
reply_textgen_parameters:
    max_new_tokens: 250 # cannot be more than 250, apparently
    num_return_sequences: 1
    temperature: 0.8
    top_k: 40
    repetition_penalty: 1.08
    stop_token: '<|endoftext|>'
    return_full_text: False
# schedule for posts.
post_schedule: ["01:00","09:00","17:00"]
# number of times to try making a post before giving up
post_tries: 3
# share of posts which are linkposts (images)
linkpost_share: 0.5
# Smaller finetuned model for posts with SSI-style tagging
post_textgen_model: ""
post_textgen_parameters:
    max_new_tokens: 250 # cannot be more than 250, apparently
    num_return_sequences: 2
    temperature: 0.8
    top_k: 40
    repetition_penalty: 1.08
    stop_token: '<|endoftext|>'
    return_full_text: True
post_flair: 'ff1e3b8e-a518-11ea-b87f-0e2836404d8b'
# restrict activity to image post submissions
linkpost_only: False
# topic classifier model
topic_classifier: "valhalla/distilbart-mnli-12-1"
# force reply to top-level comments on own posts
force_top_reply: True
# post or top-level comment topics that will trigger a comment
topic_list: ['improv','acting','role-play']
# threshold to trigger a comment
topic_threshold: 0.5
# minimum reply model (microsoft/DialogRPT-width) score to reply to comment
# score is a sigmoid, default of 0.5 corresponds to predicting at least 1 reply
min_reply_score: 0.5
# maximum number of comment levels up to accumulate in prompt
# also effectively the maximum number of levels down it can go
max_levels: 6
# maximum number of input characters per day - to manage Huggingface budgets
# default below is set so as to keep one bot within free plan limits
character_budget: 10000
# OPTIONAL, keywords that block a post or reply (ssi-bot default keywords included in script)
negative_keywords: []
# toxicity model rejection criteria
# minimum probability that a text classifies as toxic
toxicity_threshold: 0.9
